#!/usr/bin/env python3
import re
import sys
import yaml
from pathlib import Path

# Importa la funzione condivisa dal modulo lib
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from lib.latex_utils import fix_latex_escapes

def fix_yaml_frontmatter(content):
    """
    Fixes common YAML frontmatter issues generated by LLMs, 
    such as unquoted strings containing colons.
    """
    yaml_match = re.match(r'^---\n(.*?)\n---\n(.*)', content, re.DOTALL)
    if not yaml_match:
        return content

    yaml_text = yaml_match.group(1)
    body_text = yaml_match.group(2)
    
    # Fix unquoted 'topic' values containing colons
    def quote_topic(match):
        topic_val = match.group(1).strip()
        # If there's a colon and it's not already wrapped in quotes
        if ':' in topic_val and not (topic_val.startswith('"') and topic_val.endswith('"')) and not (topic_val.startswith("'") and topic_val.endswith("'")):
            # Escape inner double quotes if any, then wrap the whole string in double quotes
            topic_val = topic_val.replace('"', '\\"')
            return f'topic: "{topic_val}"'
        return match.group(0)
    
    fixed_yaml = re.sub(r'^topic:\s+(.*)$', quote_topic, yaml_text, flags=re.MULTILINE)
    return f"---\n{fixed_yaml}\n---\n{body_text}"

def fix_math_blocks(content):
    """
    Ensures that block-level LaTeX (e.g., $$...$$ containing newlines or \\begin)
    has the $$ markers on their own separate lines to comply with react-markdown.
    """
    def replacer(match):
        inner = match.group(1)
        # If the math block is multiline OR contains a LaTeX environment
        if '\n' in inner or '\\begin{' in inner:
            inner = inner.strip()
            return f"$$\n{inner}\n$$"
        else:
            return f"$${inner}$$"
            
    return re.sub(r'\$\$(.*?)\$\$', replacer, content, flags=re.DOTALL)




def process_file(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        new_content = fix_yaml_frontmatter(content)
        new_content = fix_math_blocks(new_content)
        new_content = fix_latex_escapes(new_content)
        
        # Verify YAML is now syntactically valid
        yaml_match = re.match(r'^---\n(.*?)\n---\n(.*)', new_content, re.DOTALL)
        if yaml_match:
            yaml.safe_load(yaml_match.group(1))
            
        if new_content != content:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            return True, "Fixed"
            
        return False, "Unchanged"
    except Exception as e:
        return False, f"Error: {e}"

def main():
    # Detect the submissions/pending directory robustly
    base_dir = Path(__file__).parent.parent
    pending_dir = base_dir / 'submissions' / 'pending'
    
    if not pending_dir.exists():
        print(f"Directory {pending_dir} not found.")
        sys.exit(1)
        
    print(f"Checking pending submissions in {pending_dir}...")
    fixed_count = 0
    error_count = 0
    
    for file_path in pending_dir.glob('*.md'):
        changed, msg = process_file(file_path)
        if changed:
            print(f"[FIXED] {file_path.name}")
            fixed_count += 1
        elif "Error" in msg:
            print(f"[ERROR] {file_path.name}: {msg}")
            error_count += 1
        else:
            print(f"[OK] {file_path.name}")
            
    print(f"\nDone. Fixed: {fixed_count}, Errors: {error_count}")

if __name__ == '__main__':
    main()
